apiVersion: v1
kind: ConfigMap
metadata:
  name: pj_configmap
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: pj_secret
type: Opaque
data:
  DB_PASSWORD: "mypassword"