apiVersion: v1
kind: ConfigMap
metadata:
  name: pjconfigmap
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: pjsecret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==